// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	models "mini-cms-api/models"

	mock "github.com/stretchr/testify/mock"
)

// ContentRepository is an autogenerated mock type for the ContentRepository type
type ContentRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: contentReq
func (_m *ContentRepository) Create(contentReq models.ContentRequest) (models.Content, error) {
	ret := _m.Called(contentReq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Content
	var r1 error
	if rf, ok := ret.Get(0).(func(models.ContentRequest) (models.Content, error)); ok {
		return rf(contentReq)
	}
	if rf, ok := ret.Get(0).(func(models.ContentRequest) models.Content); ok {
		r0 = rf(contentReq)
	} else {
		r0 = ret.Get(0).(models.Content)
	}

	if rf, ok := ret.Get(1).(func(models.ContentRequest) error); ok {
		r1 = rf(contentReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *ContentRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *ContentRepository) GetAll() ([]models.Content, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Content
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Content, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Content); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Content)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *ContentRepository) GetByID(id string) (models.Content, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Content
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Content, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) models.Content); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Content)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: contentReq, id
func (_m *ContentRepository) Update(contentReq models.ContentRequest, id string) (models.Content, error) {
	ret := _m.Called(contentReq, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.Content
	var r1 error
	if rf, ok := ret.Get(0).(func(models.ContentRequest, string) (models.Content, error)); ok {
		return rf(contentReq, id)
	}
	if rf, ok := ret.Get(0).(func(models.ContentRequest, string) models.Content); ok {
		r0 = rf(contentReq, id)
	} else {
		r0 = ret.Get(0).(models.Content)
	}

	if rf, ok := ret.Get(1).(func(models.ContentRequest, string) error); ok {
		r1 = rf(contentReq, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewContentRepository creates a new instance of ContentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContentRepository {
	mock := &ContentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
