// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	categories "mini-cms-api/businesses/categories"

	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: categoryReq
func (_m *UseCase) Create(categoryReq *categories.Domain) (categories.Domain, error) {
	ret := _m.Called(categoryReq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 categories.Domain
	var r1 error
	if rf, ok := ret.Get(0).(func(*categories.Domain) (categories.Domain, error)); ok {
		return rf(categoryReq)
	}
	if rf, ok := ret.Get(0).(func(*categories.Domain) categories.Domain); ok {
		r0 = rf(categoryReq)
	} else {
		r0 = ret.Get(0).(categories.Domain)
	}

	if rf, ok := ret.Get(1).(func(*categories.Domain) error); ok {
		r1 = rf(categoryReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *UseCase) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *UseCase) GetAll() ([]categories.Domain, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []categories.Domain
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]categories.Domain, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []categories.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]categories.Domain)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *UseCase) GetByID(id string) (categories.Domain, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 categories.Domain
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (categories.Domain, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) categories.Domain); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(categories.Domain)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: categoryReq, id
func (_m *UseCase) Update(categoryReq *categories.Domain, id string) (categories.Domain, error) {
	ret := _m.Called(categoryReq, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 categories.Domain
	var r1 error
	if rf, ok := ret.Get(0).(func(*categories.Domain, string) (categories.Domain, error)); ok {
		return rf(categoryReq, id)
	}
	if rf, ok := ret.Get(0).(func(*categories.Domain, string) categories.Domain); ok {
		r0 = rf(categoryReq, id)
	} else {
		r0 = ret.Get(0).(categories.Domain)
	}

	if rf, ok := ret.Get(1).(func(*categories.Domain, string) error); ok {
		r1 = rf(categoryReq, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
